=== Junhaoer/AE-1.20-UI/DarkMode/assets/ae2/screens/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://appliedenergistics.github.io/screen_style",
  "type": "object",
  "title": "AE2 Screen Style",
  "description": "Provides styling information for an AE2 UI screen",
  "required": [],
  "definitions": {
    "position": {
      "$comment": "Used to position an element in relationship to the size of the current dialog",
      "$id": "Position",
      "type": "object",
      "properties": {
        "left": {
          "type": "number",
          "description": "Positions the content to the right (positive) or left (negative) of the left screen edge."
        },
        "top": {
          "type": "number",
          "description": "Positions the content to the bottom (positive) or top (negative) of the top screen edge."
        },
        "right": {
          "type": "number",
          "description": "Positions the content to the left (positive) or right (negative) of the right screen edge."
        },
        "bottom": {
          "type": "number",
          "description": "Positions the content to the top (positive) or bottom (negative) of the bottom screen edge."
        }
      }
    },
    "color": {
      "$comment": "Definition of a color using a fake HTML notation",
      "type": "string",
      "pattern": "^#([0-9a-fA-F]{2}){3,4}$"
    },
    "text": {
      "$comment": "JSON schema definition of Minecraft text https://minecraft.wiki/w/Raw_JSON_text_format",
      "type": "object",
      "properties": {
        "extra": {
          "description": "Text that is displayed after this text, but that inherits this texts properties.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/text"
          }
        },
        "color": {
          "type": "string",
          "pattern": "^#([0-9a-fA-F]{6})$"
        },
        "font": {
          "type": "string",
          "default": "minecraft:default",
          "description": "Font in assets/<namespace>/font"
        },
        "bold": {
          "type": "boolean",
          "default": false
        },
        "italic": {
          "type": "boolean",
          "default": false
        },
        "underlined": {
          "type": "boolean",
          "default": false
        },
        "strikethrough": {
          "type": "boolean",
          "default": false
        },
        "obfuscated": {
          "type": "boolean",
          "default": false
        },
        "insertion": {
          "type": "string",
          "description": "When shift-clicked while the chat is open, the text of this property will be inserted."
        },
        "clickEvent": {
          "type": "object",
          "properties": {
            "action": {
              "type": "string",
              "enum": [
                "open_url",
                "open_file",
                "run_command",
                "suggest_command",
                "change_page",
                "copy_to_clipboard"
              ]
            },
            "value": {
              "type": "string"
            }
          },
          "required": ["action", "value"]
        },
        "hoverEvent": {
          "type": "object",
          "oneOf": [
            {
              "properties": {
                "action": {
                  "const": "show_text"
                },
                "contents": {
                  "$ref": "#/definitions/text"
                }
              }
            },
            {
              "properties": {
                "action": {
                  "const": "show_item"
                },
                "contents": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "default": "minecraft:air",
                      "description": "The item to show"
                    },
                    "count": {
                      "type": "integer",
                      "default": 1,
                      "description": "The item stack size"
                    },
                    "tag": {
                      "type": "string",
                      "description": "NBT of the item, serialized as string. See https://minecraft.wiki/w/Player.dat_format#Item_structure"
                    }
                  },
                  "required": ["id"]
                }
              }
            },
            {
              "properties": {
                "action": {
                  "const": "show_entity"
                },
                "contents": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "$ref": "#/definitions/text"
                    },
                    "type": {
                      "type": "string",
                      "default": "minecraft:pig",
                      "description": "The entity type id to show"
                    },
                    "id": {
                      "type": "string",
                      "description": "UUID of the entity to show"
                    }
                  }
                }
              }
            }
          ]
        }
      },
      "oneOf": [
        {
          "properties": {
            "text": {
              "description": "Display simple text",
              "type": "string"
            }
          },
          "required": ["text"]
        },
        {
          "properties": {
            "translate": {
              "description": "The ID of a translation key",
              "type": "string"
            },
            "with": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/text"
              }
            }
          },
          "required": ["translate"]
        },
        {
          "properties": {
            "keybind": {
              "type": "string",
              "description": "A keybind identifier"
            }
          },
          "required": ["keybind"]
        }
      ]
    },
    "rect": {
      "oneOf": [
        {
          "type": "array",
          "items": [
            {
              "type": "integer",
              "description": "x"
            },
            {
              "type": "integer",
              "description": "y"
            },
            {
              "type": "integer",
              "description": "width"
            },
            {
              "type": "integer",
              "description": "height"
            }
          ],
          "additionalItems": false
        },
        {
          "type": "object",
          "properties": {
            "x": {
              "type": "integer"
            },
            "y": {
              "type": "integer"
            },
            "width": {
              "type": "integer"
            },
            "height": {
              "type": "integer"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "blitter": {
      "type": "object",
      "properties": {
        "texture": {
          "type": "string"
        },
        "textureWidth": {
          "type": "integer",
          "default": 256
        },
        "textureHeight": {
          "type": "integer",
          "default": 256
        },
        "srcRect": {
          "$ref": "#/definitions/rect"
        }
      },
      "required": ["texture"]
    },
    "generatedBackground": {
      "type": "object",
      "properties": {
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        }
      },
      "required": ["width", "height"]
    }
  },
  "properties": {
    "includes": {
      "description": "Relative path to other files to include before processing this one.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "palette": {
      "$comment": "See PaletteColor enum",
      "type": "object",
      "description": "Defines colors used through the UI screen",
      "properties": {
        "DEFAULT_TEXT_COLOR": {
          "$ref": "#/definitions/color"
        },
        "MUTED_TEXT_COLOR": {
          "$ref": "#/definitions/color"
        },
        "SELECTION_COLOR": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_PLACEHOLDER": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_SELECTION": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_ERROR": {
          "$ref": "#/definitions/color"
        },
        "TEXTFIELD_TEXT": {
          "$ref": "#/definitions/color"
        },
        "ERROR": {
          "$ref": "#/definitions/color"
        }
      }
    },
    "background": {
      "$ref": "#/definitions/blitter"
    },
    "generatedBackground": {
      "$ref": "#/definitions/generatedBackground"
    },
    "slots": {
      "type": "object",
      "description": "Defines positions for slots and their grid alignment",
      "additionalProperties": {
        "type": "object",
        "allOf": [
          {
            "properties": {
              "grid": {
                "$comment": "Configures the slots with this semantic in a grid",
                "enum": [
                  "IO_BUS_CONFIG",
                  "BREAK_AFTER_9COLS",
                  "BREAK_AFTER_2COLS",
                  "BREAK_AFTER_3COLS",
                  "HORIZONTAL",
                  "VERTICAL"
                ]
              }
            }
          },
          {
            "$ref": "#/definitions/position"
          }
        ]
      },
      "propertyNames": {
        "$comment": "List SlotSemantic names here",
        "enum": [
          "NONE",
          "STORAGE",
          "PLAYER_INVENTORY",
          "PLAYER_HOTBAR",
          "TOOLBOX",
          "CONFIG",
          "UPGRADE",
          "STORAGE_CELL",
          "INSCRIBER_PLATE_TOP",
          "INSCRIBER_PLATE_BOTTOM",
          "AAE_ARMOR",
          "MACHINE_INPUT",
          "MACHINE_PROCESSING",
          "MACHINE_OUTPUT",
          "MACHINE_CRAFTING_GRID",
          "BLANK_PATTERN",
          "ENCODED_PATTERN",
          "VIEW_CELL",
          "CRAFTING_GRID",
          "CRAFTING_RESULT",
          "PROCESSING_PRIMARY_RESULT",
          "PROCESSING_FIRST_OPTIONAL_RESULT",
          "PROCESSING_SECOND_OPTIONAL_RESULT",
          "BIOMETRIC_CARD",
          "READONLY_STACKS",
          "AE2WTLIB_HELMET",
          "AE2WTLIB_CHESTPLATE",
          "AE2WTLIB_LEGGINGS",
          "AE2WTLIB_BOOTS",
          "AE2WTLIB_OFFHAND",
          "AE2WTLIB_TRASH",
          "AE2WTLIB_MAGNET_CARD",
          "AE2WTLIB_INFINITY_BOOSTER_CARD",
          "AE2WTLIB_PICKUP_CONFIG",
          "AE2WTLIB_INSERT_CONFIG",
          "AE2WTLIB_SINGULARITY"
        ]
      }
    },
    "text": {
      "description": "Defines text that will be shown on the UI, the property name is used to reference text from code",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "text": {
            "$ref": "#/definitions/text"
          },
          "color": {
            "$comment": "See enum PaletteColor",
            "enum": [
              "DEFAULT_TEXT_COLOR",
              "MUTED_TEXT_COLOR",
              "SELECTION_COLOR",
              "ERROR"
            ],
            "default": "DEFAULT_TEXT_COLOR"
          },
          "position": {
            "$ref": "#/definitions/position"
          },
          "centerHorizontally": {
            "type": "boolean",
            "default": false
          },
          "scale": {
            "type": "number",
            "default": 1,
            "minimum": 0.1,
            "maximum": 4,
            "$comment": "Can be used to display smaller text, 0.5 works well, usually"
          },
          "align": {
            "type": "string",
            "default": "LEFT",
            "enum": ["LEFT", "CENTER", "RIGHT"]
          },
          "maxWidth": {
            "type": "number",
            "minimum": 0,
            "default": 0,
            "description": "If greater than 0, the text will be word-wrapped when it reaches the given width in pixels."
          }
        }
      }
    },
    "tooltips": {
      "description": "Defines areas that will show a tooltip on the screen. These areas are evaluated after everything else that could show a tooltip.",
      "type": "object",
      "additionalProperties": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "tooltip": {
                "type": "array",
                "items": {
                  "$ref": "#/definitions/text"
                }
              },
              "width": {
                "type": "integer"
              },
              "height": {
                "type": "integer"
              }
            },
            "required": ["tooltip", "width", "height"]
          },
          {
            "$ref": "#/definitions/position"
          }
        ]
      }
    },
    "images": {
      "description": "Additional screen-specific images",
      "additionalProperties": {
        "$ref": "#/definitions/blitter"
      }
    },
    "helpTopic": {
      "description": "Overrides the default help topic for this screen. This will be resolved as a link to a page in the guidebook and may contain an optional fragment (#some-heading) to directly link to a heading or anchor in the page.",
      "type": "string"
    },
    "terminalStyle": {
      "description": "If this screen is a terminal, this defines required properties to display it properly",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "header": {
          "description": "The top of the terminal background right up to the first row of content.",
          "$ref": "#/definitions/blitter"
        },
        "firstRow": {
          "description": "The area to draw for the first row in the terminal. Usually this includes the top of the scrollbar.",
          "$ref": "#/definitions/blitter"
        },
        "row": {
          "description": "The area to repeat for every row in the terminal. Should be 16px for the item + 2px for the border in size.",
          "$ref": "#/definitions/blitter"
        },
        "lastRow": {
          "description": "The area to draw for the last row in the terminal. Usually this includes the top of the scrollbar.",
          "$ref": "#/definitions/blitter"
        },
        "bottom": {
          "description": "The area to draw at the bottom of the terminal (i.e. includes the player inventory).",
          "$ref": "#/definitions/blitter"
        },
        "maxRows": {
          "description": "If specified, limits the terminal to at most this many rows rather than using up available space.",
          "type": "integer",
          "minimum": 3
        },
        "slotsPerRow": {
          "description": "The number of slots per row on the background image.",
          "type": "integer",
          "minimum": 1
        },
        "searchFieldRect": {
          "description": "The bounding box of the search field in the background.",
          "$ref": "#/definitions/rect"
        },
        "sortable": {
          "description": "Defines if this terminal has a sort by button.",
          "type": "boolean",
          "default": true
        },
        "supportsAutoCrafting": {
          "description": "Defines if this terminal supports auto-crafting. If not, the button to show only craftable items is hidden.",
          "type": "boolean",
          "default": false
        },
        "stackSizeStyle": {
          "description": "The type of stack size rendering to use.",
          "type": "string",
          "default": "ITEMS",
          "enum": ["ITEMS", "FLUIDS"]
        },
        "showTooltipsWithItemInHand": {
          "type": "boolean",
          "default": false,
          "description": "Should the terminal show item tooltips for the network inventory even if the player has an item in their hand? Useful for showing fluid tooltips when the player has a bucket in hand."
        }
      }
    },
    "widgets": {
      "description": "Defines properties of various widgets that are positioned on the screen. The properties are widget-dependant. Which widget is placed is decided in code.",
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "allOf": [
          {
            "$ref": "#/definitions/position"
          },
          {
            "properties": {
              "width": {
                "type": "integer"
              },
              "height": {
                "type": "integer"
              },
              "hideEdge": {
                "description": "Used to hide the border around TabButtons",
                "type": "boolean"
              }
            }
          }
        ]
      }
    }
  }
}

=== Junhaoer/AE-1.20-UI/DarkMode/assets/ae2/screens/terminals/base_terminal.json
{
  "$schema": "../schema.json",
  "includes": [
    "../common/common.json",
    "../common/player_inventory.json",
    "../common/terminal_switch_toolbox.json"
  ],
  "terminalStyle": {
    "slotsPerRow": 9,
    "header": {
      "texture": "guis/terminal.png",
      "srcRect": [
        0,
        0,
        195,
        17
      ]
    },
    "firstRow": {
      "texture": "guis/terminal.png",
      "srcRect": [
        0,
        17,
        195,
        18
      ]
    },
    "row": {
      "texture": "guis/terminal.png",
      "srcRect": [
        0,
        35,
        195,
        18
      ]
    },
    "lastRow": {
      "texture": "guis/terminal.png",
      "srcRect": [
        0,
        53,
        195,
        18
      ]
    },
    "bottom": {
      "texture": "guis/terminal.png",
      "srcRect": [
        0,
        71,
        195,
        99
      ]
    }
  },
  "text": {
    "entriesShown": {
      "color": "DEFAULT_TEXT_COLOR",
      "align": "RIGHT",
      "scale": 0.6,
      "position": {
        "right": 26,
        "top": 8
      }
    }
  },
  "widgets": {
    "scrollbar": {
      "left": 175,
      "top": 18
    },
    "craftingStatus": {
      "left": 171,
      "top": -5,
      "hideEdge": false,
      "width": 20,
      "height": 20
    },
    "viewCells": {
      "right": -2,
      "top": -2
    },
    "search": {
      "left": 80,
      "top": 4,
      "width": 89,
      "height": 12
    }
  }
}

=== Junhaoer/AE-1.20-UI/LightMode/assets/ae2/screens/pattern_provider.json
{
  "$schema": "schema.json",
  "includes": [
    "common/common.json",
    "common/player_inventory.json",
    "common/switch_toolbox.json"
  ],
  "background": {
    "texture": "guis/pattern_provider.png",
    "srcRect": [
      0,
      0,
      176,
      215
    ]
  },
  "slots": {
    "ENCODED_PATTERN": {
      "left": 8,
      "top": 45,
      "grid": "HORIZONTAL"
    },
    "STORAGE": {
      "left": 8,
      "top": 97,
      "grid": "HORIZONTAL"
    }
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.CraftingInterface"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    },
    "interface_config": {
      "text": {
        "translate": "gui.ae2.Patterns"
      },
      "position": {
        "left": 8,
        "top": 34
      }
    },
    "interface_stored_items": {
      "text": {
        "translate": "gui.ae2.ReturnInventory"
      },
      "position": {
        "left": 8,
        "top": 86
      }
    }
  },
  "widgets": {
    "openPriority": {
      "left": 152,
      "top": -5,
      "width": 20,
      "height": 20
    },
    "lockReason": {
      "left": 5,
      "top": 15
    }
  }
}

=== Junhaoer/AE-1.20-UI/LightMode/assets/ae2/screens/terminals/terminal_settings.json
{
  "$schema": "../schema.json",
  "includes": ["../common/common.json"],
  "generatedBackground": {
    "width": 200,
    "height": 216
  },
  "text": {
    "dialog_title": {
      "position": {
        "left": 8,
        "top": 7
      },
      "text": {
        "translate": "gui.ae2.TerminalSettingsTitle"
      }
    },
    "search_settings_title": {
      "position": {
        "left": 8,
        "top": 110
      },
      "text": {
        "translate": "gui.ae2.SearchSettingsTitle"
      }
    }
  },
  "widgets": {
    "back": {
      "right": 22,
      "top": 0
    },
    "pinAutoCraftedItemsCheckbox": {
      "left": 10,
      "top": 25,
      "width": 180
    },
    "notifyForFinishedCraftingJobsCheckbox": {
      "left": 10,
      "top": 50,
      "width": 180
    },
    "clearGridOnCloseCheckbox": {
      "left": 10,
      "top": 82,
      "width": 180
    },
    "useInternalSearchRadio": {
      "left": 10,
      "top": 124,
      "width": 75
    },
    "useExternalSearchRadio": {
      "left": 95,
      "top": 124,
      "width": 75
    },
    "searchTooltipsCheckbox": {
      "left": 10,
      "top": 128,
      "width": 150
    },
    "rememberCheckbox": {
      "left": 10,
      "top": 144,
      "width": 150
    },
    "autoFocusCheckbox": {
      "left": 10,
      "top": 160,
      "width": 150
    },
    "syncWithExternalCheckbox": {
      "left": 10,
      "top": 176,
      "width": 150
    },
    "exposeInventoryExternalCheckbox": {
      "left": 10,
      "top": 192,
      "width": 150
    },
    "clearExternalCheckbox": {
      "left": 10,
      "top": 144,
      "width": 150
    }
  }
}

=== Junhaoer/AE-1.20-UI/DarkMode/assets/ae2/screens/quantum_crafter_pattern_config.json
{
  "$schema": "schema.json",
  "includes": [
    "common/common.json"
  ],
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.advanced_ae.QuantumCrafterPatternConfig"
      },
      "position": {
        "left": 10,
        "top": 5
      }
    }
  },
  "background": {
    "texture": "guis/pattern_config.png",
    "srcRect": [
      0,
      0,
      176,
      142
    ]
  },
  "widgets": {
    "scrollbar": {
      "left": 10,
      "top": 26
    },
    "back": {
      "left": 154,
      "top": 0
    }
  }
}

=== Junhaoer/AE-1.20-UI/DarkMode/assets/ae2/screens/terminals/pattern_encoding_terminal.json
{
  "$schema": "../schema.json",
  "includes": [
    "terminal.json",
    "encoding/crafting.json",
    "encoding/processing.json",
    "encoding/smithing_table.json",
    "encoding/stonecutting.json"
  ],
  "helpTopic": "items-blocks-machines/terminals.md#pattern-encoding-terminal-ui",
  "slots": {
    "BLANK_PATTERN": {
      "left": 147,
      "bottom": 165
    },
    "ENCODED_PATTERN": {
      "left": 147,
      "bottom": 118
    }
  },
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.ae2.Terminal"
      },
      "position": {
        "left": 8,
        "top": 6
      }
    },
    "crafting_grid_title": {
      "text": {
        "translate": "gui.ae2.PatternEncoding"
      },
      "position": {
        "left": 8,
        "bottom": 177
      }
    }
  },
  "terminalStyle": {
    "header": {
      "texture": "guis/pattern.png",
      "srcRect": [0, 0, 195, 17]
    },
    "firstRow": {
      "texture": "guis/pattern.png",
      "srcRect": [0, 17, 195, 18]
    },
    "row": {
      "texture": "guis/pattern.png",
      "srcRect": [0, 35, 195, 18]
    },
    "lastRow": {
      "texture": "guis/pattern.png",
      "srcRect": [0, 53, 195, 18]
    },
    "bottom": {
      "texture": "guis/pattern.png",
      "srcRect": [0, 71, 195, 180]
    }
  },
  "widgets": {
    "modeTabButton0": {
      "left": 175,
      "bottom": 174,
      "width": 22,
      "height": 22
    },
    "modeTabButton1": {
      "left": 175,
      "bottom": 153,
      "width": 22,
      "height": 22
    },
    "modeTabButton2": {
      "left": 175,
      "bottom": 132,
      "width": 22,
      "height": 22
    },
    "modeTabButton3": {
      "left": 175,
      "bottom": 111,
      "width": 22,
      "height": 22
    },
    "modePanel0": {
      "left": 9,
      "bottom": 166
    },
    "modePanel1": {
      "left": 9,
      "bottom": 166
    },
    "modePanel2": {
      "left": 9,
      "bottom": 166
    },
    "modePanel3": {
      "left": 9,
      "bottom": 166
    },
    "encodePattern": {
      "left": 147,
      "bottom": 145
    }
  }
}

=== Junhaoer/AE-1.20-UI/DarkMode/assets/ae2/screens/reaction_chamber.json
{
  "$schema": "schema.json",
  "includes": [
    "common/common.json",
    "common/player_inventory.json"
  ],
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.advanced_ae.ReactionChamber"
      },
      "position": {
        "left": 10,
        "top": 5
      }
    }
  },
  "background": {
    "texture": "guis/reaction_chamber.png",
    "srcRect": [
      0,
      0,
      176,
      180
    ]
  },
  "slots": {
    "MACHINE_INPUT": {
      "left": 42,
      "top": 24,
      "grid": "BREAK_AFTER_3COLS"
    },
    "MACHINE_OUTPUT": {
      "left": 118,
      "top": 43
    }
  },
  "images": {
    "progressBar": {
      "texture": "guis/reaction_chamber.png",
      "srcRect": [
        176,
        0,
        6,
        18
      ]
    },
    "powerAlert": {
      "texture": "guis/reaction_chamber.png",
      "srcRect": [
        182,
        0,
        18,
        18
      ]
    }
  },
  "widgets": {
    "clearFluid": {
      "left": 28,
      "top": 72
    },
    "clearFluidOut": {
      "left": 140,
      "top": 72
    },
    "progressBar": {
      "left": 140,
      "top": 42
    },
    "powerAlert": {
      "left": 117,
      "top": 68
    }
  }
}

=== Junhaoer/AE-1.20-UI/DarkMode/assets/ae2/screens/quantum_crafter.json
{
	"$schema": "schema.json",
	"includes": [
		"common/common.json",
		"common/player_inventory.json",
		"common/switch_toolbox.json"
	],
	"text": {
		"dialog_title": {
			"text": {
				"translate": "gui.advanced_ae.QuantumCrafter"
			},
			"position": {
				"left": 8,
				"top": 5
			}
		},
		"output_inv_text": {
			"text": {
				"translate": "gui.advanced_ae.OutputInventory"
			},
			"position": {
				"left": 8,
				"top": 76
			}
		}
	},
	"background": {
		"texture": "guis/quantum_crafter.png",
		"srcRect": [0, 0, 176, 219]
	},
	"slots": {
		"MACHINE_INPUT": {
			"left": 8,
			"top": 42,
			"grid": "HORIZONTAL"
		},
		"MACHINE_OUTPUT": {
			"left": 8,
			"top": 87,
			"grid": "BREAK_AFTER_9COLS"
		}
	},
	"widgets": {
		"cfgButton1": {
			"left": 8,
			"top": 24,
			"width": 16,
			"height": 16
		},
		"cfgButton2": {
			"left": 26,
			"top": 24,
			"width": 16,
			"height": 16
		},
		"cfgButton3": {
			"left": 44,
			"top": 24,
			"width": 16,
			"height": 16
		},
		"cfgButton4": {
			"left": 62,
			"top": 24,
			"width": 16,
			"height": 16
		},
		"cfgButton5": {
			"left": 80,
			"top": 24,
			"width": 16,
			"height": 16
		},
		"cfgButton6": {
			"left": 98,
			"top": 24,
			"width": 16,
			"height": 16
		},
		"cfgButton7": {
			"left": 116,
			"top": 24,
			"width": 16,
			"height": 16
		},
		"cfgButton8": {
			"left": 134,
			"top": 24,
			"width": 16,
			"height": 16
		},
		"cfgButton9": {
			"left": 152,
			"top": 24,
			"width": 16,
			"height": 16
		},
		"enableButton1": {
			"left": 9,
			"top": 60,
			"width": 12,
			"height": 12
		},
		"enableButton2": {
			"left": 27,
			"top": 60,
			"width": 12,
			"height": 12
		},
		"enableButton3": {
			"left": 45,
			"top": 60,
			"width": 12,
			"height": 12
		},
		"enableButton4": {
			"left": 63,
			"top": 60,
			"width": 12,
			"height": 12
		},
		"enableButton5": {
			"left": 81,
			"top": 60,
			"width": 12,
			"height": 12
		},
		"enableButton6": {
			"left": 99,
			"top": 60,
			"width": 12,
			"height": 12
		},
		"enableButton7": {
			"left": 117,
			"top": 60,
			"width": 12,
			"height": 12
		},
		"enableButton8": {
			"left": 135,
			"top": 60,
			"width": 12,
			"height": 12
		},
		"enableButton9": {
			"left": 153,
			"top": 60,
			"width": 12,
			"height": 12
		}
	}
}

=== Junhaoer/AE-1.20-UI/DarkMode/assets/ae2/screens/quantum_armor_filter_config.json
{
  "$schema": "schema.json",
  "includes": [
    "common/common.json",
    "common/player_inventory.json"
  ],
  "text": {
    "dialog_title": {
      "text": {
        "translate": "gui.advanced_ae.QuantumArmorSetting"
      },
      "position": {
        "left": 10,
        "top": 8
      }
    }
  },
  "background": {
    "texture": "guis/quantum_armor_filter_config.png",
    "srcRect": [
      0,
      0,
      176,
      184
    ]
  },
  "slots": {
    "CONFIG": {
      "left": 62,
      "top": 29,
      "grid": "BREAK_AFTER_3COLS"
    }
  },
  "widgets": {
    "back": {
      "left": 154,
      "top": 0
    }
  }
}
